import React, { useState, useRef } from "react";
import { CandidateProfile, SKILL_CATEGORIES, DEPARTMENTS } from "./types";
import {
  BrutalBox,
  BrutalButton,
  BrutalInput,
  BrutalTextArea,
  BrutalCheckbox,
} from "./components/BrutalComponents";
import {
  Upload,
  ArrowRight,
  Send,
  Terminal,
  Briefcase,
  AlertCircle,
  Database,
} from "lucide-react";

export default function App() {
  const [step, setStep] = useState<number>(1);
  const [isSubmitting, setIsSubmitting] = useState(false);

  const [formData, setFormData] = useState<CandidateProfile>({
    fullName: "",
    email: "",
    phone: "",
    department: "",
    skills: [],
    bio: "",
    experienceLevel: "intern",
    portfolioUrl: "",
    subscribeToNewsletter: false,
  });
  const [file, setFile] = useState<File | null>(null);

  const fileInputRef = useRef<HTMLInputElement>(null);

  const handleInputChange = (
    e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>
  ) => {
    setFormData({ ...formData, [e.target.name]: e.target.value });
  };

  const toggleSkill = (skill: string) => {
    setFormData((prev) => ({
      ...prev,
      skills: prev.skills.includes(skill)
        ? prev.skills.filter((s) => s !== skill)
        : [...prev.skills, skill],
    }));
  };

  const handleRadioChange = (name: string, value: string) => {
    setFormData((prev) => ({ ...prev, [name]: value }));
  };

  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files && e.target.files[0]) {
      setFile(e.target.files[0]);
    }
  };

  const handleNextStep1 = () => {
    if (!formData.fullName || !formData.email) {
      alert("MANDATORY FIELDS MISSING: NAME OR EMAIL");
      return;
    }
    if (!file) {
      alert("MANDATORY: YOU MUST UPLOAD A CV/RESUME.");
      return;
    }
    setStep(2);
  };

  const handleNextStep2 = () => {
    if (!formData.department) {
      alert("PLEASE SELECT A TARGET DEPARTMENT.");
      return;
    }
    if (!formData.bio) {
      alert("PLEASE PROVIDE A BIO / PITCH.");
      return;
    }
    setStep(3);
  };

  // Fallback to email if backend fails
  const generateMailto = () => {
    const recipient = "contactbrianroy@gmail.com";
    const subject = `INTERN APPLICATION [${
      formData.department
    }]: ${formData.fullName.toUpperCase()}`;

    let body = `NAME: ${formData.fullName}
EMAIL: ${formData.email}
PHONE: ${formData.phone}
DEPARTMENT: ${formData.department}
EXPERIENCE: ${formData.experienceLevel}
PORTFOLIO: ${formData.portfolioUrl}

SKILLS:
${formData.skills.map((s) => `- ${s}`).join("\n")}

BIO / PITCH:
${formData.bio}


------------------------------------------------
ATTACHMENT NOTICE:
Please find my CV attached to this email.
(User: Remember to attach '${file?.name}' before sending!)
------------------------------------------------
Generated by INTERN_OS
`;
    return `mailto:${recipient}?subject=${encodeURIComponent(
      subject
    )}&body=${encodeURIComponent(body)}`;
  };

  const handleSubmit = async () => {
    setIsSubmitting(true);

    const submitData = new FormData();
    submitData.append("fullName", formData.fullName);
    submitData.append("email", formData.email);
    submitData.append("phone", formData.phone);
    submitData.append("department", formData.department);
    submitData.append("experienceLevel", formData.experienceLevel);
    submitData.append("skills", JSON.stringify(formData.skills));
    submitData.append("bio", formData.bio);
    submitData.append("portfolioUrl", formData.portfolioUrl);
    submitData.append(
      "subscribeToNewsletter",
      String(formData.subscribeToNewsletter)
    );
    if (file) {
      submitData.append("cv", file);
    }

    try {
      // Use relative URL for Vercel deployment
      const apiUrl = import.meta.env.DEV
        ? "http://localhost:3000/api/apply"
        : "/api/apply";
      const response = await fetch(apiUrl, {
        method: "POST",
        body: submitData,
      });

      if (response.ok) {
        alert(
          "YOOO YOU'RE LOCKED IN FR FR 🔥 Application sent successfully! No cap, we'll hit you up soon mate!"
        );
        window.location.reload();
      } else {
        throw new Error("Backend Error");
      }
    } catch (error) {
      console.error(error);
      const useEmail = window.confirm(
        "YOOO YOU'RE LOCKED IN FR FR 🔥 Application sent successfully! No cap, we'll hit you up soon mate!"
      );
      if (useEmail) {
        window.location.href = generateMailto();
      }
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <div className="min-h-screen bg-brutal-bg p-4 md:p-8 font-mono selection:bg-brutal-red selection:text-white">
      {/* Header */}
      <header className="mb-12 border-b-8 border-black pb-6 max-w-5xl mx-auto">
        <h1 className="font-display text-5xl md:text-8xl uppercase leading-[0.9] tracking-tighter break-words">
          Intern<span className="text-brutal-red">_</span>Hunter
        </h1>
        <p className="mt-4 text-xl font-bold uppercase tracking-widest flex items-center gap-2">
          <Terminal size={24} />
          <span>V.1.5 // APPLICATION SYSTEM</span>
        </p>
      </header>

      <main className="max-w-4xl mx-auto pb-20">
        {/* Step Indicator */}
        <div className="mb-8 flex flex-wrap gap-4 font-bold text-sm uppercase tracking-widest">
          <div
            className={`border-2 border-black px-3 py-1 ${
              step === 1 ? "bg-black text-white" : "bg-white opacity-50"
            }`}
          >
            01. LOGISTICS
          </div>
          <div
            className={`border-2 border-black px-3 py-1 ${
              step === 2 ? "bg-black text-white" : "bg-white opacity-50"
            }`}
          >
            02. ROLE & SKILLS
          </div>
          <div
            className={`border-2 border-black px-3 py-1 ${
              step === 3 ? "bg-black text-white" : "bg-white opacity-50"
            }`}
          >
            03. EXECUTE
          </div>
        </div>

        {/* STEP 1: Personal Data & Logistics */}
        {step === 1 && (
          <div className="animate-fade-in-up">
            <BrutalBox title="LOGISTICS_DATA">
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-8">
                <BrutalInput
                  label="Full Name"
                  name="fullName"
                  placeholder="JOHN DOE"
                  value={formData.fullName}
                  onChange={handleInputChange}
                  required
                />
                <BrutalInput
                  label="Email Address"
                  name="email"
                  type="email"
                  placeholder="JOHN@EXAMPLE.COM"
                  value={formData.email}
                  onChange={handleInputChange}
                  required
                />
                <BrutalInput
                  label="Phone"
                  name="phone"
                  placeholder="+1 555 000 000"
                  value={formData.phone}
                  onChange={handleInputChange}
                />
                <BrutalInput
                  label="Portfolio URL"
                  name="portfolioUrl"
                  placeholder="HTTPS://..."
                  value={formData.portfolioUrl}
                  onChange={handleInputChange}
                />
              </div>

              {/* Experience Level */}
              <div className="mb-8 border-t-4 border-black pt-6">
                <label className="font-mono font-bold uppercase text-sm border-l-4 border-black pl-2 mb-4 block">
                  Candidate Status
                </label>
                <div className="flex gap-4">
                  {["intern", "fresher"].map((level) => (
                    <label
                      key={level}
                      className="flex items-center gap-2 cursor-pointer group"
                    >
                      <input
                        type="radio"
                        name="experienceLevel"
                        value={level}
                        checked={formData.experienceLevel === level}
                        onChange={handleInputChange}
                        className="appearance-none w-8 h-8 border-4 border-black checked:bg-brutal-red"
                      />
                      <span className="text-xl uppercase font-bold group-hover:underline">
                        {level}
                      </span>
                    </label>
                  ))}
                </div>
              </div>

              {/* Newsletter Subscription */}
              <div className="mb-8 border-t-4 border-black pt-6">
                <label className="flex items-center gap-3 cursor-pointer group">
                  <input
                    type="checkbox"
                    checked={formData.subscribeToNewsletter}
                    onChange={(e) =>
                      setFormData((prev) => ({
                        ...prev,
                        subscribeToNewsletter: e.target.checked,
                      }))
                    }
                    className="appearance-none w-8 h-8 border-4 border-black checked:bg-brutal-yellow"
                  />
                  <div>
                    <span className="font-bold uppercase group-hover:underline">
                      SIGN ME UP FOR UPDATES 📬
                    </span>
                    <p className="text-xs text-gray-500 mt-1">
                      Get notified about opportunities, no spam fr fr
                    </p>
                  </div>
                </label>
              </div>

              {/* File Upload - MANDATORY */}
              <div className="mt-8 border-t-4 border-black pt-6">
                <label className="font-mono font-bold uppercase text-sm border-l-4 border-black pl-2 mb-4 flex items-center justify-between text-red-600">
                  <span className="flex items-center gap-2">
                    <AlertCircle size={16} /> CV / Resume File
                  </span>
                  <span className="font-black bg-red-600 text-white px-2">
                    REQUIRED
                  </span>
                </label>
                <div
                  onClick={() => fileInputRef.current?.click()}
                  className={`
                    border-4 border-dashed p-8 text-center cursor-pointer transition-colors group relative
                    ${
                      file
                        ? "border-brutal-blue bg-blue-50"
                        : "border-red-500 bg-red-50 hover:bg-brutal-yellow"
                    }
                  `}
                >
                  <input
                    type="file"
                    ref={fileInputRef}
                    className="hidden"
                    onChange={handleFileChange}
                    accept=".pdf,.doc,.docx"
                  />
                  <Upload
                    className={`w-12 h-12 mx-auto mb-4 transition-transform ${
                      file ? "text-brutal-blue" : "text-red-500"
                    } group-hover:scale-110`}
                  />
                  <p className="font-bold uppercase">
                    {file
                      ? `FILE LOCKED: ${file.name}`
                      : "DRAG FILE OR CLICK TO UPLOAD"}
                  </p>
                  <p className="text-xs mt-2 text-gray-600 uppercase">
                    PDF, DOCX accepted
                  </p>
                </div>
              </div>

              <div className="mt-8 flex justify-end">
                <BrutalButton onClick={handleNextStep1}>
                  Proceed to Role{" "}
                  <ArrowRight className="inline ml-2" size={18} />
                </BrutalButton>
              </div>
            </BrutalBox>
          </div>
        )}

        {/* STEP 2: Department, Skills & Bio */}
        {step === 2 && (
          <div className="animate-fade-in-up">
            <BrutalBox title="ROLE_CONFIGURATION">
              {/* Departments Section */}
              <div className="mb-10">
                <label className="font-mono font-bold uppercase text-sm border-l-4 border-black pl-2 mb-4 flex justify-between">
                  <span className="flex items-center gap-2">
                    <Briefcase size={16} /> Target Department
                  </span>
                  <span className="text-brutal-red text-xs font-black">
                    * REQ
                  </span>
                </label>
                <div className="grid grid-cols-2 md:grid-cols-3 gap-3">
                  {DEPARTMENTS.map((dept) => (
                    <label
                      key={dept}
                      className={`
                      border-4 border-black p-3 cursor-pointer transition-all hover:shadow-hard-sm flex items-center gap-2
                      ${
                        formData.department === dept
                          ? "bg-brutal-blue text-white"
                          : "bg-white"
                      }
                    `}
                    >
                      <input
                        type="radio"
                        name="department"
                        value={dept}
                        checked={formData.department === dept}
                        onChange={(e) =>
                          handleRadioChange("department", e.target.value)
                        }
                        className="appearance-none w-4 h-4 border-2 border-current checked:bg-brutal-yellow"
                      />
                      <span className="font-bold text-sm">{dept}</span>
                    </label>
                  ))}
                </div>
              </div>

              <div className="mb-10 border-t-4 border-black pt-8">
                <label className="font-mono font-bold uppercase text-lg border-b-4 border-black pb-1 mb-6 block w-max">
                  Capabilities Loadout
                </label>

                {Object.entries(SKILL_CATEGORIES).map(([category, skills]) => (
                  <div key={category} className="mb-6">
                    <h4 className="font-bold text-xs uppercase text-gray-500 mb-2 tracking-widest">
                      {category.replace("_", " & ")}
                    </h4>
                    <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-2">
                      {skills.map((skill) => (
                        <BrutalCheckbox
                          key={skill}
                          label={skill}
                          checked={formData.skills.includes(skill)}
                          onChange={() => toggleSkill(skill)}
                        />
                      ))}
                    </div>
                  </div>
                ))}
              </div>

              <BrutalTextArea
                label="The Pitch (Bio)"
                name="bio"
                placeholder="TELL ME WHY YOU ARE THE BEST. KEEP IT RAW."
                value={formData.bio}
                onChange={handleInputChange}
                className="min-h-[150px]"
                required
              />

              <div className="mt-8 flex justify-between items-center flex-wrap gap-4">
                <BrutalButton variant="secondary" onClick={() => setStep(1)}>
                  Back
                </BrutalButton>

                <BrutalButton variant="primary" onClick={handleNextStep2}>
                  Review Application{" "}
                  <ArrowRight className="inline ml-2" size={18} />
                </BrutalButton>
              </div>
            </BrutalBox>
          </div>
        )}

        {/* STEP 3: Review & Submit */}
        {step === 3 && (
          <div className="animate-fade-in-up">
            <div className="max-w-3xl mx-auto">
              {/* Review Data */}
              <BrutalBox title="PAYLOAD_REVIEW">
                <div className="space-y-6 font-mono text-sm md:text-base">
                  <div className="bg-brutal-yellow border-2 border-black p-4 text-center">
                    <h3 className="font-display text-xl uppercase mb-2">
                      Ready to Send
                    </h3>
                    <p className="font-bold">TARGET: DB & DRIVE STORAGE</p>
                  </div>

                  <div className="grid md:grid-cols-2 gap-6">
                    <div>
                      <span className="bg-black text-white px-1 font-bold">
                        CANDIDATE
                      </span>
                      <div className="border-l-4 border-black pl-3 mt-1 py-1">
                        <p className="font-bold text-lg">{formData.fullName}</p>
                        <p>{formData.email}</p>
                        <p>{formData.phone}</p>
                      </div>
                    </div>

                    <div>
                      <span className="bg-black text-white px-1 font-bold">
                        POSITIONING
                      </span>
                      <div className="border-l-4 border-black pl-3 mt-1 py-1">
                        <p>
                          <span className="font-bold">DEPT:</span>{" "}
                          {formData.department}
                        </p>
                        <p>
                          <span className="font-bold">LEVEL:</span>{" "}
                          {formData.experienceLevel.toUpperCase()}
                        </p>
                      </div>
                    </div>
                  </div>

                  <div>
                    <span className="bg-black text-white px-1 font-bold">
                      SKILLS LOADOUT
                    </span>
                    <div className="mt-2 border-2 border-black p-3 bg-gray-50">
                      {formData.skills.length > 0 ? (
                        <div className="flex flex-wrap gap-2">
                          {formData.skills.map((s) => (
                            <span
                              key={s}
                              className="bg-gray-200 px-2 py-1 text-xs font-bold border border-black"
                            >
                              {s}
                            </span>
                          ))}
                        </div>
                      ) : (
                        <span className="opacity-50">NO SKILLS SELECTED</span>
                      )}
                    </div>
                  </div>

                  <div>
                    <span className="bg-black text-white px-1 font-bold">
                      PITCH
                    </span>
                    <p className="mt-2 border-2 border-black p-3 bg-gray-50 whitespace-pre-wrap">
                      {formData.bio}
                    </p>
                  </div>

                  {file ? (
                    <div className="border-4 border-black p-4 bg-brutal-blue text-white flex items-center justify-between">
                      <span className="font-bold flex items-center gap-2">
                        <Briefcase size={20} /> ATTACHMENT READY
                      </span>
                      <span className="font-mono text-sm underline">
                        {file.name}
                      </span>
                    </div>
                  ) : (
                    <div className="border-4 border-red-500 p-4 bg-red-100 text-red-600 font-bold uppercase text-center">
                      FATAL ERROR: NO CV ATTACHED
                    </div>
                  )}
                </div>
              </BrutalBox>

              <div className="mt-8 text-center">
                <BrutalButton
                  onClick={handleSubmit}
                  loading={isSubmitting}
                  className="w-full md:w-auto text-xl md:text-3xl py-6 px-12 hover:scale-[1.02] active:scale-95 shadow-[8px_8px_0px_0px_#000] hover:shadow-[12px_12px_0px_0px_#000]"
                >
                  <Database className="inline mr-4" size={28} />
                  INITIATE UPLOAD
                </BrutalButton>
                <p className="mt-4 text-xs font-bold text-gray-500">
                  SECURE TRANSMISSION TO DATABASE
                </p>
                <div className="mt-6">
                  <BrutalButton
                    variant="secondary"
                    onClick={() => setStep(2)}
                    className="text-sm py-2"
                  >
                    EDIT PAYLOAD
                  </BrutalButton>
                </div>
              </div>
            </div>
          </div>
        )}
      </main>

      <footer className="max-w-5xl mx-auto border-t-8 border-black pt-8 flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
        <div className="font-mono text-sm">
          <p>© 2024 INTERN_OS. ALL RIGHTS RESERVED.</p>
          <p className="opacity-50">SYSTEM STATUS: ONLINE</p>
        </div>
        <div className="flex gap-4">
          <a
            href="/admin"
            className="bg-brutal-yellow text-black px-2 font-bold hover:bg-brutal-red hover:text-white transition-colors"
          >
            ADMIN
          </a>
          <a
            href="https://www.instagram.com/brianroymathew"
            target="_blank"
            rel="noopener noreferrer"
            className="bg-black text-white px-2 hover:bg-brutal-red hover:text-white transition-colors"
          >
            INSTAGRAM
          </a>
          <a
            href="https://www.linkedin.com/in/brianroymathew"
            target="_blank"
            rel="noopener noreferrer"
            className="bg-black text-white px-2 hover:bg-brutal-blue hover:text-white transition-colors"
          >
            LINKEDIN
          </a>
        </div>
      </footer>
    </div>
  );
}
